# requirements
snowflake-snowpark-python
streamlit

name: app_environment
channels:
  - snowflake
dependencies:
  - snowflake-snowpark-python
  - streamlit
  - python=3.8.*
  - snowflake-snowpark-python=
  - streamlit=
