# requirements
snowflake-snowpark-python
streamlit

name: app_environment
channels:
  - snowflake
dependencies:
  - python=3.8.*
  - snowflake-snowpark-python=
  - streamlit=
  - snowflake-connector-python==2.8.3
